// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/emotion-vars.css";
import "../styles/page-emotions.css";
import Nav from "../components/ui/Nav";
import AIEmotionSystem from "../components/ui/AIEmotionSystem";
import Footer from "@/components/ui/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI-Powered Portfolio | Real Emotion Detection",
  description: "Portfolio with real AI emotion detection using transformers",
  icons: {
    icon: [{ url: '/icon_wbg.png', sizes: '32x32', type: 'image/png' }],
    shortcut: '/icon_wbg.png',
    apple: [{ url: '/icon_wbg.png', sizes: '180x180', type: 'image/png' }],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/icon_wbg.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/icon_wbg.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/icon_wbg.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased emotion-aware`}
      >
        <Nav />
        <AIEmotionSystem />
        {children}
        <Footer />
      </body>
    </html>
  );
}
